### ISSUE TITLE
Consume on 5v With bed

### ISSUE THREAD

**Issue by feiltom** [Traumflug/Generation_7_Electronics#23]
Hello i don t understand why when i turn on my heated bed i have 1.5A on 5v.
Sorry for my english

**Comment by Traumflug** [comment]
I don't even understand what you're talking about. Is it about a SevenSwitch?

**Comment by feiltom** [comment]
no on my Gen7 Board-AVR 1.5
I have inverse heated bed with my jHead  and same problem
it is mount with  RLB 8743
thanck you

**Comment by feiltom** [comment]
I thinck the common ground on 5v and 12v give me a false result on my ammeter
